CREATE OR REPLACE FUNCTION comments_delete (
  id INTEGER
) RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
  BEGIN
    DELETE
    FROM "comments"
    WHERE "id" = $1;

    RETURN FOUND;
  END;
$$;